### ISSUE TITLE
Week 2 Homework : Read Online Articles

### ISSUE THREAD

**Issue by akallish** [IITIDIDX597/sp_2021_team1#2]
IBM Hills Overview : []https://ibm.co/2AfH2yA
Agile Terminology : []http://bit.ly/2uwt8Va

**Comment by akallish** [comment]
@JSpragueDesign @sliu131 @zixuan-zhaozhao please move this task to the product backlog pipeline and when ready to initiate the task, please move it to the in progress pipeline. Remember that all asynchronous task conversations need to happen in the GitHub tasks found in the issues tab. To reference people, use their GitHub handle. If you need help reference @akallish and I will get a notification. Thanks.

**Comment by JSpragueDesign** [comment]
@JSpragueDesign has completed this

**Comment by JSpragueDesign** [comment]
Jeff has completed this

**Comment by akallish** [comment]
> Jeff has completed this

@JSpragueDesign good job. Thanks for being the first one in your group to complete a task.

**Comment by JSpragueDesign** [comment]
Hey Team,
Something that was part of the Pre-Work reading, but has really stuck with me is IBM's definition of design:

"At IBM, we define design as the intent behind an outcome. "

I really like this way of thinking because it broadens what design is, and is more inclusive to how technical people use the word design (eg design a circuit board, design a process).

It also doesn't box designers in as the doers (eg people who draw logos), but empowers designers to set intentions for larger challenges.

I took this mindset into the IBM Hills reading and really enjoyed their approach

**Comment by akallish** [comment]
> Hey Team,
> Something that was part of the Pre-Work reading, but has really stuck with me is IBM's definition of design:
> 
> "At IBM, we define design as the intent behind an outcome. "
> 
> I really like this way of thinking because it broadens what design is, and is more inclusive to how technical people use the word design (eg design a circuit board, design a process).
> 
> It also doesn't box designers in as the doers (eg people who draw logos), but empowers designers to set intentions for larger challenges.
> 
> I took this mindset into the IBM Hills reading and really enjoyed their approach

@JSpragueDesign i am glad hills make sense to you. This was a hard concept to have IBM embrace but it really is the bridge between the big idea and how to deliver it.

**Comment by kanalchhajed** [comment]
Kanal completed this

**Comment by zixuan-zhaozhao** [comment]
Zixuan completed this
